language: node_js

node_js:
- '6.0.0'

branches:
  only:
  - hexo                # 只监测 source 分支上的 commit

before_install:
- npm install -g hexo-cli # 安装 hexo

install:
- npm install             # 安装额外的插件

script:
# - git submodule init      # 用于更新主题
# - git submodule update
- hexo generate

after_success:
- git config --global user.name "mayongze"
- git config --global user.email "1014057907@qq.com"
- hexo deploy